using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lib.Db.TvpGen;

/// <summary>
/// 사용자 코드를 정적으로 분석하여 런타임 설정을 상수로 '구워주는(Baking)' 제너레이터입니다.
/// <para>
/// <b>[기능]</b>
/// - `AddLibDbHybridCache` 호출 여부 감지 -> `IsHybridCacheEnabled` 상수 생성
/// - AOT 환경을 위한 정적 바인딩 헬퍼 생성 (Reserved)
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class StaticBakingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. AddLibDbHybridCache 호출 감지
        var hybridCacheCallProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateInvocation(s),
                transform: static (ctx, _) => IsRealHybridCacheInvocation(ctx))
            .Where(static match => match)
            .Collect()
            .Select(static (matches, _) => matches.Length > 0); // 하나라도 있으면 true

        // 2. 소스 생성
        context.RegisterSourceOutput(hybridCacheCallProvider, Execute);
    }

    private static bool IsCandidateInvocation(SyntaxNode node)
    {
        // 간단한 1차 필터: 메서드 호출이면서 이름이 "AddLibDbHybridCache" 인 것
        return node is InvocationExpressionSyntax inv &&
               inv.Expression is MemberAccessExpressionSyntax mae &&
               mae.Name.Identifier.ValueText == "AddLibDbHybridCache";
    }

    private static bool IsRealHybridCacheInvocation(GeneratorSyntaxContext context)
    {
        // 2차 정밀 필터: 심볼 확인 (실제 확장 메서드인지)
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

        return symbol != null && 
               symbol.Name == "AddLibDbHybridCache" &&
               symbol.ContainingType.Name == "HybridCacheExtensions";
    }

    private static void Execute(SourceProductionContext spc, bool isHybridCacheEnabled)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Static Baking Generator");
        sb.AppendLine("namespace Lib.Db.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 컴파일 타임에 분석된 Lib.Db 정적 설정입니다.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static partial class LibDbStaticConfiguration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// HybridCache 활성화 여부 (정적 분석 결과)");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public const bool IsHybridCacheEnabled = {isHybridCacheEnabled.ToString().ToLowerInvariant()};");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("LibDbStaticConfiguration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
