using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lib.Db.TvpGen;

/// <summary>
/// 사용자 코드를 정적으로 분석하여 런타임 설정을 상수로 '구워주는(Baking)' 제너레이터입니다.
/// <para>
/// <b>[기능]</b>
/// - `AddLibDbHybridCache` 호출 여부 감지 -> `IsHybridCacheEnabled` 상수 생성
/// - AOT 환경을 위한 정적 바인딩 헬퍼 생성 (Reserved)
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class StaticBakingGenerator : IIncrementalGenerator
{
    /// <summary>
    /// 인크리멘털 제너레이터를 초기화하고 <c>AddLibDbHybridCache</c> 호출 감지 파이프라인을 구성합니다.
    /// </summary>
    /// <param name="context">인크리멘털 제너레이터 초기화 컨텍스트</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. AddLibDbHybridCache 호출 감지
        var hybridCacheCallProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateInvocation(s),
                transform: static (ctx, _) => IsRealHybridCacheInvocation(ctx))
            .Where(static match => match)
            .Collect()
            .Select(static (matches, _) => matches.Length > 0); // 하나라도 있으면 true

        // 2. 소스 생성
        context.RegisterSourceOutput(hybridCacheCallProvider, Execute);
    }

    /// <summary>
    /// 구문 노드가 <c>AddLibDbHybridCache</c> 메서드 호출 후보인지 1차 필터링합니다.
    /// </summary>
    /// <param name="node">검사할 구문 노드</param>
    /// <returns>후보 호출이면 <see langword="true"/></returns>
    private static bool IsCandidateInvocation(SyntaxNode node)
    {
        // 간단한 1차 필터: 메서드 호출이면서 이름이 "AddLibDbHybridCache" 인 것
        return node is InvocationExpressionSyntax inv &&
               inv.Expression is MemberAccessExpressionSyntax mae &&
               mae.Name.Identifier.ValueText == "AddLibDbHybridCache";
    }

    /// <summary>
    /// 의미론적 모델(Semantic Model)을 사용하여 실제 <c>HybridCacheExtensions.AddLibDbHybridCache</c> 확장 메서드 호출인지 2차 검증합니다.
    /// </summary>
    /// <param name="context">제너레이터 구문 컨텍스트 (의미론적 모델 포함)</param>
    /// <returns>실제 HybridCache 등록 호출이면 <see langword="true"/></returns>
    private static bool IsRealHybridCacheInvocation(GeneratorSyntaxContext context)
    {
        // 2차 정밀 필터: 심볼 확인 (실제 확장 메서드인지)
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
        var method = symbol?.ReducedFrom ?? symbol;

        return method != null &&
               method.Name == "AddLibDbHybridCache" &&
               method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   == "global::Lib.Db.Extensions.HybridCacheExtensions";
    }

    /// <summary>
    /// HybridCache 활성화 여부를 담은 <c>LibDbStaticConfiguration</c> 소스 파일을 생성합니다.
    /// </summary>
    /// <param name="spc">소스 생성 컨텍스트</param>
    /// <param name="isHybridCacheEnabled">HybridCache 등록 호출이 감지되었으면 <see langword="true"/></param>
    private static void Execute(SourceProductionContext spc, bool isHybridCacheEnabled)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Static Baking Generator");
        sb.AppendLine("namespace Lib.Db.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 컴파일 타임에 분석된 Lib.Db 정적 설정입니다.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static partial class LibDbStaticConfiguration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// HybridCache 활성화 여부 (정적 분석 결과)");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public const bool IsHybridCacheEnabled = {isHybridCacheEnabled.ToString().ToLowerInvariant()};");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("LibDbStaticConfiguration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
